In [18]:
import numpy as np
s=np.array([1,2,3,4,5]])
print(s)

[[1 2 3 4 5]]


In [10]:
#2 dimension
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a)
print(a.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [20]:
#3 dimension
import numpy as np
a=np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(a)
print(a.ndim)
           
           

[[[1 2 3 4 5]
  [6 7 8 9 0]]]
3


In [15]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9,0])
print(b[2])

3


In [17]:
#slicing
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9,0])
print(b[2:6])

[3 4 5 6]


In [22]:
#indexing
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b[0,4])

5


In [43]:
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b[0,4])
print(b[1,4])
#slicing
print(b[0,1:4])

5
0
[2 3 4]


In [44]:
import numpy as np
a=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(a[1,1])

[6 7 8 9 0]
